spring:
    servlet:
        multipart:
            enabled: true
            max-file-size: 128MB
            max-request-size: 128MB
    application:
        name: sdc
    cloud:
        consul:
            host: ${NM_CONSUL_HOST:172.16.0.3}
            port: ${NM_CONSUL_PORT:8500}
        discovery:
            health-check-interval: 30s
            health-check-timeout: 10s
            enabled: true
            instance-id: sdc
            service-name: sdc
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    #读写分离
    db-master:
        name: test
        url: jdbc:mysql://${MYSQL_HOST:172.16.0.64}:${MYSQL_PORT:8806}/saas_sdc?useSSL=false&useUnicode=true&allowMultiQueries=true&characterEncoding=UTF8
        username: ${URANUS_MYSQL_MASTER_USERNAME:root}
        password: ${URANUS_MYSQL_MASTER_PASSWORD:aurora12)(*&}
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 20
        initialSize: 5
        maxWait: 3000
        minIdle: 5
        timeBetweenEvictionRunsMillis: 6000
        minEvictableIdleTimeMillis: 30000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    db-slave:
        name: test
        url: jdbc:mysql://${MYSQL_HOST:172.16.0.64}:${MYSQL_PORT:8806}/saas_sdc?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8
        username: ${URANUS_MYSQL_SLAVE_USERNAME:root}
        password: ${URANUS_MYSQL_SLAVE_PASSWORD:aurora12)(*&}
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 20
        initialSize: 5
        maxWait: 3000
        minIdle: 5
        timeBetweenEvictionRunsMillis: 6000
        minEvictableIdleTimeMillis: 30000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
        # Redis服务器地址
        host: ${NM_REDIS_HOST:172.16.0.25}
        # Redis服务器连接端口
        port: ${NM_REDIS_PORT:6378}
        database: 0
        jedis:
            pool:
                max-active: 300
                # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1
                # 连接池中的最大空闲连接
                max-idle: 300
                # 连接池中的最小空闲连接
                min-idle: 50
            commandTimeout: 5000
        password: ${NM_REDIS_PASSWORD:crs-litpd7r1:nome@redis!}
mybatis:
    basepackage: cn.nome.saas.sdc.repository.dao
    mapper-locations: "classpath*:mapper/**/*.xml"
vertica:
    datasource:
        url: jdbc:vertica://${VERTICAL_HOST:172.20.252.12}:5433/km
        username: BiRead
        password: BiRead123
        driverClassName: com.vertica.jdbc.Driver
ribbon:
    ConnectionTimeout: 2000
    ReadTimeout: 5000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: true
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5500
server:
    port: ${NM_SERVICE_PORT:9001} #启动端口
    tomcat:
        max-connections: 1000 # 默认值
        max-threads: 1000 # 默认值
        accesslog:
            buffered: true
            directory: ${ACCESS_LOG_PATH:/nmapps/logs/java/pd-sdc}
            enabled: true
            pattern: "%a|%A|%p|%t|'%r'|'HEADER-NOME-CorpID:%{HEADER-NOME-CorpID}i'|'HEADER-NOME-AppID:%{HEADER-NOME-AppID}i'|'HEADER-NOME-UID:%{HEADER-NOME-UID}i'|%s|%Dms|%I|'User-Agent:%{User-Agent}i'|'Referer:%{Referer}i'"
            prefix: ${ACCESS_LOG_NAME:access_log}
            suffix: .log
            file-date-format: .yyyy-MM-dd
            request-attributes-enabled: false
            rename-on-rotate: true
logging:
    level:
        root: ERROR
        org.springframework.web: ERROR
        org.springframework.cloud.consul: INFO
        cn.nome.saas: INFO
    file: ${LOG_FILE_PATH:/home/log/sdc/pd-sdc.log}
    pattern:
        file: "%d{yyyy-MM-dd HH:mm:ss}|[%thread]|%-5level|%logger-|[TxId:%X{PtxId},SpanId:%X{PspanId}]|%msg%n"

nome:
    guan-yuan:
        domain-id: nome
        url: http://lh.nome.cn
        private-key: "MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAIqRImExuWq3m247KCjB4ddeJmQ/XNmf/XnWZWHFDYNhqNR8LCUpVICjT7UcNwdMiPHRcYpWB64ez+2oU7UlDD+W4e2KQlPWbGL0VX08eSzVmNbiUlF68i+upL47BhKX1LIVZ4Yar8RfVqB9YTvB2aeOBXLoMF1j/vFUAusbvUIPAgMBAAECgYAPKfrdMBfeeeFkmsy2SSFx9De3WMfMeRnAL5pArNPhwNo9Bqm+F1vMCBM8+q16+wExlX4baXbFs1GF7JnchQVl9tEFOZOLVlfC5+XiB7/eKGG5XeLIh0XdsAutLctuO5iCu6UdcphWsmXbskcUzyZQUsitUM8tQC4TTIgBi0fxIQJBAMamfvsCier9o3zEoHSavQPZnGYWzkmEPxPuUROzFYlUPRL6MyLcwmWkd4vF9O8+LdCLsOc7azuKQeJRtkZeW2UCQQCykhioWb3b5uwGmcngN1GvMvVlGN/IQoBQIlKLY7FGzQuiV95UR8Dp+Hl3Jakd4eI2zP5YdjqRtPQreHMcIqJjAkBoSR3eXn3S7Ka4KG1n6ZgS/lm5yn0vYQrQRssvgVNsDdomLU1NHwG65HWR3jFwq37XvY34RlxMHI/r5SPAm2Z1AkBWro6jojSEe5sVNTAG1DOlrUHr2mA+8PEidRbGrRUP/lbobmjxVodxy/kCeliWteC+o1HQFUwnEMT6GRUfkjxrAkBUKqoxypKMk9g1GymjEzg7LS/3HkVTjfGZoWxw47/DORePpUsIZy3CbSVaElzpAN3YpRdTHdEmeEon7yG04nIf"