spring:
    servlet:
        multipart:
            enabled: true
            max-file-size: 128MB
            max-request-size: 128MB
    application:
        name: sdc
    cloud:
        consul:
            host: 172.16.0.91
            port: 30085
            discovery:
                health-check-interval: 30s
                health-check-timeout: 10s
                enabled: true
                instance-id: pd-sdc
                service-name: pd-sdc
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    #读写分离
    db-master:
        name: saas_sdc
        url: jdbc:mysql://gz-cdb-qdpjjjmr.sql.tencentcdb.com:62051/saas_sdc?useSSL=false&useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
        username: root
        password: nmdb0518!@#
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 20
        initialSize: 5
        maxWait: 3000
        minIdle: 5
        timeBetweenEvictionRunsMillis: 6000
        minEvictableIdleTimeMillis: 30000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    db-slave:
        name: saas_sdc
        url: jdbc:mysql://gz-cdb-qdpjjjmr.sql.tencentcdb.com:62051/saas_sdc?useSSL=false&useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
        username: root
        password: nmdb0518!@#
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 20
        initialSize: 5
        maxWait: 3000
        minIdle: 5
        timeBetweenEvictionRunsMillis: 6000
        minEvictableIdleTimeMillis: 30000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    druid:
        filters: stat
        max-active: 20
        initial-size: 1
        max-wait: 60000
        min-idle: 1
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-open-prepared-statements: 20
        async-init: true
        validation-query: select 'x'
    redis:
        host: 172.16.0.91
        port: 30079
        database: 0
        jedis:
            pool:
                max-active: 300
                # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1
                # 连接池中的最大空闲连接
                max-idle: 300
                # 连接池中的最小空闲连接
                min-idle: 50
            commandTimeout: 5000
        password: nmredis666
mybatis:
    mapper-locations: "classpath*:mapper/**/*.xml"
ribbon:
    ConnectionTimeout: 2000
    ReadTimeout: 5000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: true
#大数据db
vertica:
    datasource:
        #    url: jdbc:vertica://192.168.59.54:5433/km
        url: jdbc:vertica://${VERTICAL_HOST:172.20.252.12}:5433/km
        username: BiRead
        password: BiRead123
        driverClassName: com.vertica.jdbc.Driver
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5500
server:
    port: 38089
    tomcat:
        max-connections: 1000 # 默认值
        max-threads: 1000 # 默认值
        accesslog:
            buffered: true
            directory: ${ACCESS_LOG_PATH:/nmapps/logs/java/pd-sdc}
            enabled: true
            pattern: "%a|%A|%p|%t|'%r'|'HEADER-NOME-CorpID:%{HEADER-NOME-CorpID}i'|'HEADER-NOME-AppID:%{HEADER-NOME-AppID}i'|'HEADER-NOME-UID:%{HEADER-NOME-UID}i'|%s|%Dms|%I|'User-Agent:%{User-Agent}i'|'Referer:%{Referer}i'"
            prefix: ${ACCESS_LOG_NAME:access_log}
            suffix: .log
            file-date-format: .yyyy-MM-dd
            request-attributes-enabled: false
            rename-on-rotate: true
logging:
    level:
        root: ERROR
        org.springframework.web: ERROR
        org.springframework.cloud.consul: INFO
        cn.nome.saas: INFO
    file: ${LOG_FILE_PATH:/home/log/sdc/pd-sdc.log}
    pattern:
        file: "%d{yyyy-MM-dd HH:mm:ss}|[%thread]|%-5level|%logger-|[TxId:%X{PtxId},SpanId:%X{PspanId}]|%msg%n"
management:
    endpoint:
        health:
            probes:
                enabled: true
                show-details: always
nome:
    guan-yuan:
        domain-id: nome
        url: http://lh.nome.cn
        private-key: "xxx"