spring:
  application:
    name: goods-allocation
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 数据源配置
ai_portal:
  datasource:
    url: jdbc:mysql://${MYSQL_PORTAL_HOST:172.20.253.196}:${MYSQL_PORTAL_PORT:3307}/ai_portal?useUnicode=true&characterEncoding=UTF8
    username: ${MYSQL_PORTAL_USER:root}
    password: ${MYSQL_PORTAL_PASSWORD:Root!!2018}
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 5
    minIdle: 5
    maxWait: 5000
    timeBetweenEvictionRunsMillis: 6000
    minEvictableIdleTimeMillis: 30000
portal:
  datasource:
    url: jdbc:mysql://${MYSQL_PORTAL_HOST:172.20.253.196}:${MYSQL_PORTAL_PORT:3307}/allocation_portal?useUnicode=true&characterEncoding=UTF8
    username: ${MYSQL_PORTAL_USER:root}
    password: ${MYSQL_PORTAL_PASSWORD:Root!!2018}
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 5
    minIdle: 5
    maxWait: 5000
    timeBetweenEvictionRunsMillis: 6000
    minEvictableIdleTimeMillis: 30000

allocation:
  datasource:
    url: jdbc:mysql://gz-cdb-qdpjjjmr.sql.tencentcdb.com:62051/goods_allocation?useSSL=false&useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: nmdb0518!@#
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 5
    minIdle: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
        filters: stat
        max-active: 20
        initial-size: 1
        max-wait: 60000
        min-idle: 1
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-open-prepared-statements: 20
        async-init: true
        validation-query: select 'x'

vertical:
  datasource:
    #url: jdbc:vertica://172.20.250.1:5433/km
    url: jdbc:vertica://172.20.252.12:5433/km
    username: BiRead
    password: BiRead123
    driverClassName: com.vertica.jdbc.Driver
    maxActive: 50
    initialSize: 20
    minIdle: 5
    maxWait: 30000
    timeBetweenEvictionRunsMillis: 40000
    minEvictableIdleTimeMillis: 40000

vertica:
  datasource:
    #url: jdbc:vertica://172.20.250.1:5433/km
    url: jdbc:vertica://172.20.252.12:5433/km
    username: BiRead
    password: BiRead123
    driverClassName: com.vertica.jdbc.Driver
    maxActive: 20
    initialSize: 5
    minIdle: 5
    maxWait: 10000
    timeBetweenEvictionRunsMillis: 15000
    minEvictableIdleTimeMillis: 30000

server:
  port: 8101 #启动端口
  servlet.context-path: /goods-allocation
  servlet.session.timeout: 21600
  tomcat:
    max-connections: 1000 # 默认值
    max-threads: 1000 # 默认值

logging:
  level:
    root: INFO
    cn.nome.saas.allocation: INFO
  file: ${LOG_FILE_PATH:/home/log/goods-allocation/goods-allocation.log}
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n"

nome:
  portal:
    url: http://newpbdv2.bk.nome.cn
  wx:
    agentId: 1000043
    corpId: wwd3dbe39874780025
    secret: 59Z_XMe12vS1CMUxlcruSwsCq_g1VoUDwl0RQP-K7cM
    user_secret: _vAH6Vk2rlQOvsaLT1-Z002KSaw5JGhrMmSZ02221tg


#陈列管理xls模版
download:
  xls:
    template:
      dir: /home/template/
      display_category: 陈列类别配置.xlsx
      display_goods: 商品陈列配置.xlsx
      shop_display: 门店陈列配置.xlsx
      shop_info: 门店信息配置.xlsx
      forbidden_import: 禁配(白名单)导入模板.xlsx
      security_import: 保底导入模板.xlsx
      forbidden_desc: 【统一】禁配明细导入模版.xlsx
      forbidden_batch_del: 【统一】禁配明细删除模版.xlsx
      new_goods_range_import: 新品铺货范围导入模板.xlsx
      new_goods_invalid_import: 失效时间导入模板.xlsx

upload:
  xls:
    forbidden:
      dir: /home/template/upload/forbidden/

forbidden:
  switch: open

express:
  rate: 0.05


#goods barcode batch size
matcode:
  barcode:
    batch:
      size: 1500

#清空表名
scheduler:
  truncate:
    table:
      names: issue_operate_log,issue_detail,issue_in_stock,issue_mid_category_qty,issue_need_stock,issue_out_stock,issue_undo,issue_goods_data,issue_category_data,issue_midcategory_data,issue_out_stock_remain
      switch: 1
  run:
    issue:
      switch: 0
  bak:
    table:
      switch: 0
  recalc:
    shop:
      switch: 0
all:
  area:
    level: 华南一[A]华南二[A]华东[A]华中[A]华北[A]西南[A]西北[A]东北[A]中区[A]西区[A]南区[A]北区[A]北区-北[A]华南二-南[A]华南二-中[A]西区-北[A]西区-南[A]
    name: 全盘


clothing:
  allocation:
    switch: 0
  validGoods:
    switch: 0

mop:
  host: mop2.bk.nome.cn
sdc:
  host: sdc.bk.nome.cn
pdc:
  host: pdc.bk.nome.cn