debug: false
spring:
    application:
        name: pd-search
    cloud:
        consul:
          host: 172.16.0.3
          port: 8500
        discovery:
          enabled: true
          instance-id: pd-search
          service-name: pd-search
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
      name: test
      url: jdbc:mysql://${NEPTUNE_MYSQL_MASTER_HOST:172.16.0.11}:${NEPTUNE_MYSQL_MASTER_PORT:8806}/${DB_NAME:saas_search}?useUnicode=true&characterEncoding=UTF8
      username: ${NEPTUNE_MYSQL_MASTER_USERNAME:root}
      password: ${NEPTUNE_MYSQL_SLAVE_PASSWORD:aurora12)(*&}
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

    redis:
    # Redis服务器地址
        host: ${NM_REDIS_HOST:172.16.0.25}
    # Redis服务器连接端口
        port: ${NM_REDIS_PORT:6378}
        database: 0
        password: ${NM_REDIS_PASSWORD:crs-litpd7r1:nome@redis!}
        jedis:
            pool:
              max-active: 500
              # 连接池最大阻塞等待时间（使用负值表示没有限制）
              max-wait: -1
              # 连接池中的最大空闲连接
              max-idle: 200
              # 连接池中的最小空闲连接
              min-idle: 50
            commandTimeout: 5000

    data:
      elasticsearch:
#        cluster-name: ${ES_CLS_NAME:nome-elk}
#        cluster-nodes: 172.16.0.35:9300,172.16.0.37:9300,172.16.0.38:9300
        cluster-name: ${ES_CLS_NAME:elasticsearch}
        cluster-nodes: 172.16.128.11:9300
        repositories:
          enabled: true

mybatis:
    basepackage: cn.nome.saas.search.repository.dao
    mapper-locations: "classpath*:mapper/**/*.xml"

server:
    port: 8330
    tomcat:
      max-connections: 200 # 默认值
      max-threads: 200 # 默认值

logging:
  level:
    root: info
    #org.springframework.web: DEBUG
    org.springframework.cloud.consul: warn
    cn.nome.saas.search: info
    cn.nome.saas.search.repository.dao: info
  file: ${LOG_FILE_PATH:/nmapps/logs/java/search/pd-search.log}
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n"

#test
remote_ext_dict_path: D:/nmapps/logs/search/remote-dict.txt

#图片域名
IMG_DOMAIN_URL: http://storage2.nome.cn/